import type {CSSProperties} from "react";

export const primer = {
  color: {
    canvasDefault: "#ffffff",
    canvasSubtle: "#f6f8fa",
    canvasInset: "#eff2f5",
    foregroundDefault: "#1f2328",
    foregroundMuted: "#59636e",
    foregroundSubtle: "#6e7781",
    foregroundOnEmphasis: "#ffffff",
    accent: "#0969da",
    accentEmphasis: "#0550ae",
    accentMuted: "#ddf4ff",
    success: "#1a7f37",
    successEmphasis: "#1f883d",
    successMuted: "#dafbe1",
    attention: "#9a6700",
    attentionMuted: "#fff8c5",
    danger: "#cf222e",
    borderDefault: "#d0d7de",
    borderMuted: "#d8dee4",
    borderSubtle: "rgba(31, 35, 40, 0.15)",
    neutralEmphasis: "#6e7781",
    codeCanvas: "#0d1117",
    codeBorder: "#30363d",
    codeMuted: "#8b949e",
    codeBlue: "#79c0ff",
  },
  font: {
    sans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans SC', Helvetica, Arial, sans-serif",
    mono: "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
    weight: {regular: 400, medium: 500, semibold: 600},
  },
  text: {
    titleLarge: {fontSize: 32, lineHeight: "48px"},
    titleMedium: {fontSize: 20, lineHeight: "32px"},
    bodyLarge: {fontSize: 16, lineHeight: "24px"},
    bodyMedium: {fontSize: 14, lineHeight: "20px"},
    caption: {fontSize: 12, lineHeight: "16px"},
  },
  space: {1: 4, 2: 8, 3: 16, 4: 24, 5: 32, 6: 40, 7: 48},
  radius: {small: 3, medium: 6, large: 12, full: 9999},
  shadow: {
    resting: "0 1px 0 rgba(31, 35, 40, 0.04)",
    floating: "0 8px 24px rgba(140, 149, 159, 0.2)",
  },
  layout: {
    pageInset: 72,
    headerHeight: 64,
    contextHeight: 64,
    contentTop: 176,
    contentHeight: 816,
    stageWidth: 1280,
    sidebarLeft: 1376,
    sidebarWidth: 472,
  },
} as const;

export const surfaceStyle: CSSProperties = {
  background: primer.color.canvasDefault,
  border: `1px solid ${primer.color.borderDefault}`,
  borderRadius: primer.radius.medium,
  boxShadow: primer.shadow.resting,
};
